namespace SuperOffice.WebPanel
{
    public class Constants
    {
        public const string ClientId = "";
        public const string ClientSecret = "";
        public const string SuperOfficeEnvironment = "https://sod2.superoffice.com/";
        public const string RefreshTokenUri = "login/common/oauth/tokens?grant_type=refresh_token&";
        public const string RefreshTokenRedirectUrl = "https://localhost:44383/callback";
        public const string WebPanelUrl = "/api/v1/List/WebPanel/Items";
        public const string WebPanelWindowName = "AutoGeneratedPanel";
        public const string WebPanelDescription = "Web panel created by REST client";
        public const string UrlForWebPanelToDisplay = "https://community.superoffice.com/en/customer/news/product/superoffice-g9/g9-vision/";
        public const string ProgID = "web_panel_rest_generate";
        public const string UserContextClaimType = "http://schemes.superoffice.net/identity/ctx";
        public const string UserGroupUrl = "/api/v1/List/28/Items/";
        public const string UserGroups = "/UserGroups";
    }
}
