namespace SuperOffice.WebPanel
{
    public class Constants
    {
        public const string ClientId = "5b56fa500c60854ae6104d915af344bc";
        public const string ClientSecret = "0262287fb1ee764c29ab4fc979843af9";
        public const string SuperOfficeEnvironment = "https://sod2.superoffice.com/";
        //public const string AddressApiUrl = "/api/v1/Contact/";
        //public const string AddressFilter = "?$select=Address";
        public const string RefreshTokenUri = "login/common/oauth/tokens?grant_type=refresh_token&";
        public const string RefreshTokenRedirectUrl = "https://localhost:44383/callback";
        public const string WebPanelUrl = "/api/v1/List/WebPanel/Items";
        //public const string WebPanelName = "Auto Generated panel";
        public const string WebPanelWindowName = "AutoGeneratedPanel";
        public const string WebPanelDescription = "Web panel created by REST client";
        public const string UrlForWebPanelToDisplay = "https://locationpreview.azurewebsites.net/map?companyID=<cuid>&userContext=<uctx>";
        public const string ProgID = "web_panel_rest_generate";
        public const string UserContextClaimType = "http://schemes.superoffice.net/identity/ctx";
        public const string UserGroupUrl = "/api/v1/List/28/Items/";
        public const string UserGroups = "/UserGroups";
    }
}
